name: CI for Data Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Checkout CI feedback
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          echo "requirements.txt found, installing dependencies..."
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
        else
          echo "No requirements.txt found, skipping dependency installation."
        fi

    - name: Run tests
      run: bash project/tests.sh
